jobs:
  - job: test
    pool:
      vmImage: "windows-2019"
    steps:
      - script: |
                    powershell Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
                    powershell choco new choco-podman-machine-turnkey
                    powershell git clone https://github.com/ttu-capstone-podman/choco-podman-machine-turnkey.git C:\choco-podman-machine-turnkey\Install
                    powershell cd C:\choco-podman-machine-turnkey\Install
                    powershell ./choco-podman
                    powershell podman-machine --version