jobs:
  - job: test
    pool:
      vmImage: "windows-2019"
    steps:
      - script: Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) |
                    choco new choco-podman-machine-turnkey |
                    git clone https://github.com/ttu-capstone-podman/choco-podman-machine-turnkey.git C:\choco-podman-machine-turnkey\Install |
                    cd C:\choco-podman-machine-turnkey\Install |
                    ./choco-podman |
                    podman-machine --version